pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r . public
    - rm -rf public/.git public/.github public/.gitlab-ci.yml
  artifacts:
    paths:
      - public
  only:
    - main
    - master