const raziyain_dataSet=[
    [
        "1",
        "قَالَ: أَبُو مُحَمَّدٍ عَبْدُ الرَّحْمَنِ بْنُ أَبِي حَاتِمٍ: سَأَلْتُ أَبِي وَأَبَا زُرْعَةَ عَنْ مَذَاهِبِ أَهْلِ السُّنَّةِ فِي أُصُولِ الدِّينِ ، وَمَا أَدْرَكَا عَلَيْهِ الْعُلَمَاءَ فِي جَمِيعِ الْأَمْصَارِ ، وَمَا يَعْتَقِدَانِ مِنْ ذَلِكَ ، فَقَالَا:\n\n\" أَدْرَكْنَا الْعُلَمَاءَ فِي جَمِيعِ الْأَمْصَارِ حِجَازًا وَعِرَاقًا وَشَامًا وَيَمَنًا فَكَانَ مِنْ مَذْهَبِهِمُ:\n\nالْإِيمَانُ قَوْلٌ وَعَمَلٌ ، يَزِيدُ وَيَنْقُصُ ،",
        "އަބޫ މުޙައްމަދު ޢަބްދުއްރަޙްމާން ބިން އަބޫ ޙާތިމް (އައްރާޒީ) ވިދާޅުވިއެވެ: ތިމަންނަގެ ބައްޕަ (އަބޫ ޙާތިމް އައްރާޒީ) އަދި އަބޫ ޒުރްޢާ (އައްރާޒީ) ގެ އަރިހުގައި، ދީނުގެ އުސޫލުތަކާ ގުޅޭ ގޮތުން ސުންނަތުގެ އަހްލުވެރިންގެ މަޒްހަބުތަކަކީ ކޮބައިތޯ ތިމަން އެހީމެވެ. އަދި ހުރިހާ ރަށްތަކެއްގައި އިލްމުވެރިން ތިއްބެވި ކަމަށް އެ ދެބޭކަލުން ފެނިފައިވާ ގޮތަކީ ކޮބައިތޯ އެހީމެވެ. އަދި އެކަމުގައި އެ ދެބޭކަލުންގެ އަގީދާއަކީ ކޮބައިތޯ އެހީމެވެ. ފަހެ އެ ދެބޭކަލުން ޖަވާބުގައި ވިދާޅުވިއެވެ:\n\nހުރިހާ ރަށްތަކެއްގައި، ޙިޖާޒާއި، ޢިރާޤާއި، ޝާމް އަދި ޔަމަނުގައިވެސް ތިއްބެވި އިލްމުވެރިން އަހަރެމެން ބައްދަލުވެ ދުށީމެވެ. އެ ބޭފުޅުންގެ މަޒްހަބުގައި ވަނީ:\n\nއީމާންކަމަކީ ބަހާއި އަމަލެވެ. އެ އިތުރުވެ އުނިވެގެންދެއެވެ.",
        "He (i.e. `Abdur-Rahmaan ibn Abee Haatim)[2] said: I asked my father and Aboo Zur`ah -radiyallaahu `anhumaa- about the positions of the Ahlus-Sunnah (the People of the Sunnah) regarding the fundamentals of the Religion, and what they found the scholars upon in all of the cities, and what they held as their creed in that regard, so they both said: We found the scholars in all of the cities: in the Hijaaz, in `Iraaq, in Egypt, in Shaam, in Yemen, so it was from their position that [3]:\n\nEemaan (true Faith) is speech and action, it increases and decreases [4];",
        ""
    ],
    [
        "2",
        "وَالْقُرْآنُ كَلَامُ اللَّهِ غَيْرُ مَخْلُوقٍ بِجَمِيعِ جِهَاتِهِ ،",
        "އަދި ޤުރްއާނަކީ ﷲ ގެ ކަލާމްފުޅެވެ. އެއީ އެއްވެސް ގޮތަކުން މަޚްލޫޤެއް ނޫނެވެ.",
        "And the Qur’aan is the Speech of Allaah, it is not created, in all its aspects [5];\n",
        ""
    ],
    [
        "3",
        "وَالْقَدَرُ خَيْرُهُ وَشَرُّهُ مِنَ اللَّهِ عَزَّ وَجَلَّ ، وَخَيْرُ ،",
        "އަދި ގަޟާގަދަރު، އޭގެ ހެވާ ނުބައިވެސް ވަނީ ﷲ ޢައްޒަ ވަޖައްލަގެ ފަރާތުންނެވެ.",
        "And Predecree, its good and its bad, is from Allaah (the Mighty and Majestic) [6];",
        ""
    ],
    [
        "4",
        "وَخَيْرُ هَذِهِ الْأُمَّةِ بَعْدَ نَبِيِّهَا عَلَيْهِ الصَّلَاةُ وَالسَّلَامُ أَبُو بَكْرٍ الصِّدِّيقُ ، ثُمَّ عُمَرُ بْنُ الْخَطَّابِ ، ثُمَّ عُثْمَانُ بْنُ عَفَّانَ ، ثُمَّ عَلِيُّ بْنُ أَبِي طَالِبٍ عَلَيْهِمُ السَّلَامُ ، وَهُمُ الْخُلَفَاءُ الرَّاشِدُونَ الْمَهْدِيُّونَ ،",
        "އަދި މި އުންމަތުން ނަބިއްޔާއަށް ފަހު އެންމެ ހެޔޮވެގެންވަނީ އަބޫ ބަކްރު އައްޞިއްދީގެވެ. އެއަށްފަހު ޢުމަރު ބިން އަލްޚައްޠާބެވެ. އެއަށްފަހު ޢުޘްމާން ބިން ޢައްފާނެވެ. އެއަށްފަހު ޢަލީ ބިން އަބީ ޠާލިބެވެ. އަދި އެ ބޭކަލުންނަކީ ހިދާޔަތް ލިބިފައިވާ (ހަތަރު) ޚަލީފާއިންނެވެ.",
        "And the best one of this nation, after its Prophet -`alaihis-Salaam- is Aboo Bakr as-Siddeeq, then `Umar ibn al-Khattaab, then `Uthmaan ibn `Affaan, then `Alee ibn Abee Taalib -radiyallaahu `anhum [7]; and they are the rightly-guided, orthodox Caliphs [8];",
        ""
    ],
    [
        "5",
        "وَأَنَّ الْعَشَرَةَ الَّذِينَ سَمَّاهُمْ رَسُولُ اللَّهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ وَشَهِدَ لَهُمْ بِالْجَنَّةِ عَلَى مَا شَهِدَ بِهِ رَسُولُ اللَّهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ وَقَوْلُهُ الْحَقُّ ،",
        "އަދި ސުވަރުގޭގައި ވާނެކަމަށް ރަސޫލު ﷲ ﷺ ނަންގެންނެވި އަދި އެ ބޭކަލުންނަށް ހެކިވެވަޑައިގެންނެވި ދިހަ ބޭކަލުން ވަނީ، ހަމަ ރަސޫލު ﷲ ﷺ ހެކިވެވަޑައިގެންނެވި ގޮތަށެވެ. އަދި އެ ނަބިއްޔާގެ ބަސްފުޅަކީ ހައްގު ތެދެވެ.",
        "And that the ten whom Allaah”s Messenger صلى الله عليه وسلم mentioned by name, and for whom he bore witness that they will be in Paradise, are just as Allaah”s Messenger صلى الله عليه وسلم bore witness to, and his saying is the truth [9];",
        ""
    ],
    [
        "6",
        "وَالتَّرَحُّمُ عَلَى جَمِيعِ أَصْحَابِ مُحَمَّدٍ وَالْكَفُّ عَمَّا شَجَرَ بَيْنَهُمْ.",
        "އަދި މުޙައްމަދު ﷺ ގެ ހުރިހާ ސަހާބީންނަށް ރަހުމަތްލެއްވުން އެދި ދުއާ ކުރުމާއި، އެ ބޭކަލުންގެ މެދުގައި އުފެދުނު ދެބަސްވުންތަކާ ބެހޭ ގޮތުން ހަނުތިބުމެވެ.",
        "And to supplicate for mercy upon all of the companions of Muhammad صلى الله عليه وسلم , and upon his true followers, and to withhold from whatever occurred between them [10];",
        ""
    ],
    [
        "7",
        "وَأَنَّ اللَّهَ عَزَّ وَجَلَّ عَلَى عَرْشِهِ بَائِنٌ مِنْ خَلْقِهِ كَمَا وَصَفَ نَفْسَهُ فِي كِتَابِهِ ، وَعَلَى لِسَانِ رَسُولِهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ بِلَا كَيْفٍ ، أَحَاطَ بِكُلِّ شَيْءٍ عِلْمًا ، {لَيْسَ كَمِثْلِهِ شَيْءٌ وَهُوَ السَّمِيعُ الْبَصِيرُ}",
        "އަދި الله ވޮޑިގެންވަނީ އެ އިލާހުގެ ޢަރުޝީގެ މަތީގައި ކަމާއި، އެ އިލާހުގެ ޚަލްގުތަކުންނާ ވަކިވެގެންކަމެވެ. އެއީ ﷲ ގެ ފޮތުގައި އަދި އެ އިލާހުގެ ރަސޫލާގެ ދޫފުޅުން އެ އިލާހުގެ ނަފްސުފުޅު ސިފަ ކުރައްވަވާފައިވާ ފަދައިންނެވެ. އެއީ ކިހިނެތްތޯ އެހުމަކާ ނުލައެވެ. އެ އިލާހުގެ އިލްމުފުޅުން ހުރިހާ އެއްޗެއް ދެނެވޮޑިގެންވެއެވެ. \"އެ އިލާހާ އެއްފަދަ އެއްވެސް އެއްޗެއް ނުވެއެވެ. އަދި އެ އިލާހީ ހުރިހާ  އެއްޗެއް މޮޅަށް އައްސަވާވޮޑިގެންވާ، ބައްލަވާވޮޑިގެންވާ އިލާހެވެ.\"",
        "And that Allaah is (upon His Throne),[11] separate from His creation, just as He described Himself in His Book and upon the tongue of His Messenger, without describing how. He encompassed everything with Knowledge: [[ Meaning: There is nothing like Him, and He is the All-Hearing, the All-Seeing.]] [13]",
        ""
    ],
    [
        "8",
        "",
        "",
        "And Allaah -the Exalted and Most High- will be seen in the Hereafter; (and) the inhabitants of Paradise will see Him with their eyes, and they will hear His Speech, however He wishes, and just as He wishes [14];",
        ""
    ],
    [
        "9",
        "",
        "",
        "And Paradise is true, and the Fire is true, and they are both already created: they will never come to an end. So Paradise is a reward for His beloved and obedient servants; and the Fire is a punishment for those who are disobedient to Him, except for those whom Allaah -the Mighty and Majestic- has mercy upon [15];",
        ""
    ],
    [
        "10",
        "",
        "",
        "And the Siraat is true [16];",
        ""
    ],
    [
        "11",
        "",
        "",
        "And the Balance (al-Meezaan) -which has two balance-plates, upon which the deeds of the servants will be weighed: the good and the bad- is true [17];",
        ""
    ],
    [
        "12",
        "",
        "",
        "And the Vast Reservoir (al-Hawd) which our Prophet صلى الله عليه وسلم has been honoured with is true;",
        ""
    ],
    [
        "13",
        "",
        "",
        "And the Intercession (ash-Shafaa`ah) is true [18];",
        ""
    ],
    [
        "14",
        "",
        "",
        "And that some people, from the people of Tawheed, will come out from the Fire through intercession, is true;",
        ""
    ],
    [
        "15",
        "",
        "",
        "And the punishment of the grave (`Adhaabul-Qabr) is true; and Munkar and Nakeer are true; and the noble Angels who write down deeds (al-Kiraamul-Kaatiboon) are true [19];",
        ""
    ],
    [
        "16",
        "",
        "",
        "And the Resurrection (al-Ba`th) after death is true;",
        ""
    ],
    [
        "17",
        "",
        "",
        "And those guilty of major sins (Ahlul-Kabaa’ir) are under the Will of Allaah -the Mighty and Majestic; and we do not declare the people of the Qiblah to be Disbelievers on account of their sins, and we entrust their secrets to Allaah -the Mighty and Majestic [20];",
        ""
    ],
    [
        "18",
        "",
        "",
        "And we establish the obligation of the Jihaad and the Hajj along with the rulers of the Muslims in every age and time; and we do not hold rebelling against the rulers (nor fighting in time of discord)[21]; and we hear and obey whomever Allaah -the Mighty and Majestic- places in charge of our affair, and we do not remove our hand from obedience; and we follow the Sunnah and the Jamaa`ah, and we avoid isolation, differing, and splitting;",
        ""
    ],
    [
        "19",
        "",
        "",
        "And that Jihaad continues, from the time when Allaah -the Mighty and Majestic- sent His Prophet صلى الله عليه وسلم until the establishment of the Hour, along with those in authority over affairs from the rulers of the Muslims, nothing abolishes it [22];",
        ""
    ],
    [
        "20",
        "",
        "",
        "And the same is the case with the Hajj; and the charity due upon cattle is to be handed over to those in authority from the rulers of the Muslims ;",
        ""
    ],
    [
        "21",
        "",
        "",
        "And the people are treated as Believers with regard to their rulings and their inheritance, but it is not known what their actual condition with Allaah -the Mighty and Majestic- is [23];",
        ""
    ],
    [
        "22",
        "",
        "",
        "So whoever says that he is a true Believer, then he is an innovator;",
        ""
    ],
    [
        "23",
        "",
        "",
        "And whoever says that he is a Believer according to Allaah, then he is one of the liars;",
        ""
    ],
    [
        "24",
        "",
        "",
        "And whoever says: I am indeed a Believer in Allaah, then he is correct;",
        ""
    ],
    [
        "25",
        "",
        "",
        "And the Murji·ah are innovators, astray [24];",
        ""
    ],
    [
        "26",
        "",
        "",
        "And the Qadariyyah are innovators, astray; so whoever from them denies that Allaah -the Mighty and Majestic- knows whatever will occur, before it exists, then he is a Disbeliever [25];",
        ""
    ],
    [
        "27",
        "",
        "",
        "And the Jahmiyyah are Disbelievers [26];",
        ""
    ],
    [
        "28",
        "",
        "",
        "And the Raafidah have rejected Islaam [27];",
        ""
    ],
    [
        "29",
        "",
        "",
        "And the Khawaarij are renegades [28];",
        ""
    ],
    [
        "30",
        "",
        "",
        "And whoever claims that the Qur’aan is a created thing, then he is a Disbeliever in Allaah -the Tremendous, guilty of Disbelief which takes him out of the Religion; and whoever doubts about his being a Disbeliever, from those who have understanding, then he is a Disbeliever [29];",
        ""
    ],
    [
        "31",
        "",
        "",
        "And whoever doubts regarding the Speech of Allaah -the Mighty and Majestic, and so withholds concerning it, doubting, and saying: ” I do not know whether it is created or not created”, then he is a Jahmee [30];",
        ""
    ],
    [
        "32",
        "",
        "",
        "And whoever withholds regarding the Qur’aan out of ignorance, then he is to be taught, and he is declared to be guilty of innovation, but he is not declared to be a Disbeliever;",
        ""
    ],
    [
        "33",
        "",
        "",
        "And whoever says: “My recital of the Qur’aan is created”, then he is a Jahmee; or: “The Qur’aan with my recitation is created”, then he is a Jahmee;",
        ""
    ],
    [
        "34",
        "",
        "",
        "",
        ""
    ],
    [
        "35",
        "",
        "",
        "",
        ""
    ],
    [
        "36",
        "",
        "",
        "",
        ""
    ],
    [
        "37",
        "",
        "",
        "",
        ""
    ],
    [
        "38",
        "",
        "",
        "",
        ""
    ],
    [
        "39",
        "",
        "",
        "",
        ""
    ],
    [
        "40",
        "",
        "",
        "",
        ""
    ],
    [
        "41",
        "",
        "",
        "",
        ""
    ],
    [
        "42",
        "",
        "",
        "",
        ""
    ],
    [
        "43",
        "",
        "",
        "",
        ""
    ],
    [
        "44",
        "",
        "",
        "",
        ""
    ],
    [
        "45",
        "",
        "",
        "",
        ""
    ],
    [
        "46",
        "",
        "",
        "",
        ""
    ],
    [
        "47",
        "",
        "",
        "",
        ""
    ],
    [
        "48",
        "",
        "",
        "",
        ""
    ],
    [
        "49",
        "",
        "",
        "",
        ""
    ],
    [
        "50",
        "",
        "",
        "",
        ""
    ],
    [
        "51",
        "",
        "",
        "",
        ""
    ],
    [
        "52",
        "",
        "",
        "",
        ""
    ],
    [
        "53",
        "",
        "",
        "",
        ""
    ],
    [
        "54",
        "",
        "",
        "",
        ""
    ],
    [
        "55",
        "",
        "",
        "",
        ""
    ],
    [
        "56",
        "",
        "",
        "",
        ""
    ],
    [
        "57",
        "",
        "",
        "",
        ""
    ],
    [
        "58",
        "",
        "",
        "",
        ""
    ],
    [
        "59",
        "",
        "",
        "",
        ""
    ],
    [
        "60",
        "",
        "",
        "",
        ""
    ],
    [
        "61",
        "",
        "",
        "",
        ""
    ],
    [
        "62",
        "",
        "",
        "",
        ""
    ],
    [
        "63",
        "",
        "",
        "",
        ""
    ],
    [
        "64",
        "",
        "",
        "",
        ""
    ],
    [
        "65",
        "",
        "",
        "",
        ""
    ],
    [
        "66",
        "",
        "",
        "",
        ""
    ],
    [
        "67",
        "",
        "",
        "",
        ""
    ],
    [
        "68",
        "",
        "",
        "",
        ""
    ],
    [
        "69",
        "",
        "",
        "",
        ""
    ],
    [
        "70",
        "",
        "",
        "",
        ""
    ],
    [
        "71",
        "",
        "",
        "",
        ""
    ],
    [
        "72",
        "",
        "",
        "",
        ""
    ],
    [
        "73",
        "",
        "",
        "",
        ""
    ]
]