name: Mirror to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        run: |
          git push --prune --force https://oauth2:${{ secrets.GITLAB_TOKEN }}@://gitlab.com refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*
