name: Mirror to Codeberg

on:
  push:
    branches:
      - main
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: cssnr/mirror-repository-action@v1
        with:
          url: https://codeberg.org/hadithmv/pages.git
          username: hadithmv
          password: ${{ secrets.CODEBERG_TOKEN }}
          create: true
