name: Mirror to GitLab

on:
  push:
    branches:
      - main
      - master
      - gh-pages

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/hadithmv/hadithmv.gitlab.io.git
          git push gitlab main --force-with-lease
          git push gitlab --tags
