name: Mirror to Codeberg

on:
  push:
    branches:
      - main
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove large unrelated folders
        run: |
          rm -rf app androidApp-kt windowsApp-tauri codebase node_modules

      - name: Create orphan commit and push to Codeberg
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout --orphan codeberg-mirror
          git add -A
          git commit -m "Mirror: exclude app/ and build folders"
          git push --force https://hadithmv:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/hadithmv/pages.git codeberg-mirror:main
